In [20]:
import pandas as pd

In [21]:
# read csv file summary.csv
df = pd.read_csv('summary.csv')

In [22]:
df.head()

,run_id,env_id,model,temperature,attempt_idx,n_eval_episodes,seed,mean_reward,std_reward,min_reward,max_reward,total_env_steps,n_failures,status,policy_path,trace_path
0,one_shot_Pendulum-v1_llama3.1_8b_temp0.0_attem...,Pendulum-v1,llama3.1:8b,0.0,0,10,42,-1105.627011,361.932627,-1714.409098,-519.721883,2000,0,valid,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...
1,one_shot_Pendulum-v1_llama3.1_8b_temp0.0_attem...,Pendulum-v1,llama3.1:8b,0.0,1,10,43,-1155.329731,305.748894,-1707.669381,-879.107998,2000,0,valid,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...
2,one_shot_Pendulum-v1_llama3.1_8b_temp0.0_attem...,Pendulum-v1,llama3.1:8b,0.0,2,10,44,-1252.225387,357.810406,-1866.519250,-879.107998,2000,0,valid,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...
3,one_shot_Pendulum-v1_llama3.1_8b_temp0.0_attem...,Pendulum-v1,llama3.1:8b,0.0,3,10,45,-1228.125230,350.015593,-1866.519250,-879.107998,2000,0,valid,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...
4,one_shot_Pendulum-v1_llama3.1_8b_temp0.0_attem...,Pendulum-v1,llama3.1:8b,0.0,4,10,46,-1272.984671,330.618820,-1866.519250,-883.249363,2000,0,valid,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...,/home/jarnedemoen/Documents/LLM_Policy_vs_RL_C...

In [23]:
df_valid = df[df["n_failures"] == 0]

df_summary = df.groupby("temperature").apply(
    lambda g: pd.Series({
        "mean_reward_mean": g.loc[g["n_failures"] == 0, "mean_reward"].mean(),
        "mean_reward_std": g.loc[g["n_failures"] == 0, "mean_reward"].std(),
        "valid_runs": (g["n_failures"] == 0).sum(),
        "best_run": g.loc[g["n_failures"] == 0, "mean_reward"].max(),
    })
).reset_index()

df_summary = df_summary.round(3)
df_summary

/tmp/ipykernel_308612/3244490253.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_summary = df.groupby("temperature").apply(

   temperature  mean_reward_mean  mean_reward_std  valid_runs  best_run
0          0.0         -1202.858           70.189         5.0 -1105.627
1          0.4         -1287.799           36.489         4.0 -1247.412
2          0.8         -1522.251          233.701         4.0 -1298.382